apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "mongodb-ha.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "mongodb-ha.name" . }}
  ports:
    - port: {{ .Values.mongodb.service.port }}